import { Holiday, Book, Class } from '@/types';

export const DEFAULT_HOLIDAYS: Holiday[] = [
  // 2025
  { id: 'h1', date: '2025-01-01', name: 'New Year\'s Day', type: 'national', year: 2025 },
  { id: 'h2', date: '2025-01-28', name: 'Lunar New Year', type: 'national', year: 2025 },
  { id: 'h3', date: '2025-01-29', name: 'Lunar New Year', type: 'national', year: 2025 },
  { id: 'h4', date: '2025-01-30', name: 'Lunar New Year', type: 'national', year: 2025 },
  { id: 'h5', date: '2025-03-01', name: 'Independence Movement Day', type: 'national', year: 2025 },
  { id: 'h6', date: '2025-05-05', name: 'Children\'s Day', type: 'national', year: 2025 },
  { id: 'h7', date: '2025-05-06', name: 'Buddha\'s Birthday', type: 'national', year: 2025 },
  { id: 'h8', date: '2025-06-06', name: 'Memorial Day', type: 'national', year: 2025 },
  { id: 'h9', date: '2025-08-15', name: 'Liberation Day', type: 'national', year: 2025 },
  { id: 'h10', date: '2025-10-03', name: 'National Foundation Day', type: 'national', year: 2025 },
  { id: 'h11', date: '2025-10-05', name: 'Chuseok', type: 'national', year: 2025 },
  { id: 'h12', date: '2025-10-06', name: 'Chuseok', type: 'national', year: 2025 },
  { id: 'h13', date: '2025-10-07', name: 'Chuseok', type: 'national', year: 2025 },
  { id: 'h14', date: '2025-10-09', name: 'Hangeul Day', type: 'national', year: 2025 },
  { id: 'h15', date: '2025-12-25', name: 'Christmas', type: 'national', year: 2025 },
  
  // 2026
  { id: 'h26_1', date: '2026-01-01', name: 'New Year\'s Day', type: 'national', year: 2026 },
  { id: 'h26_2', date: '2026-02-16', name: 'Lunar New Year', type: 'national', year: 2026 },
  { id: 'h26_3', date: '2026-02-17', name: 'Lunar New Year', type: 'national', year: 2026 },
  { id: 'h26_4', date: '2026-02-18', name: 'Lunar New Year', type: 'national', year: 2026 },
  { id: 'h26_5', date: '2026-03-01', name: 'Independence Movement Day', type: 'national', year: 2026 },
  { id: 'h26_6', date: '2026-05-05', name: 'Children\'s Day', type: 'national', year: 2026 },
  { id: 'h26_7', date: '2026-05-24', name: 'Buddha\'s Birthday', type: 'national', year: 2026 },
  { id: 'h26_8', date: '2026-06-06', name: 'Memorial Day', type: 'national', year: 2026 },
  { id: 'h26_9', date: '2026-08-15', name: 'Liberation Day', type: 'national', year: 2026 },
  { id: 'h26_10', date: '2026-09-24', name: 'Chuseok', type: 'national', year: 2026 },
  { id: 'h26_11', date: '2026-09-25', name: 'Chuseok', type: 'national', year: 2026 },
  { id: 'h26_12', date: '2026-09-26', name: 'Chuseok', type: 'national', year: 2026 },
  { id: 'h26_13', date: '2026-10-03', name: 'National Foundation Day', type: 'national', year: 2026 },
  { id: 'h26_14', date: '2026-10-09', name: 'Hangeul Day', type: 'national', year: 2026 },
  { id: 'h26_15', date: '2026-12-25', name: 'Christmas', type: 'national', year: 2026 },
];

export const SAMPLE_CLASSES: Class[] = [
  { id: 'c_m3', name: 'M3', year: 2026, level_group: 'Middle', weekly_sessions: 2, sessions_per_month: 24, start_time: '18:10', end_time: '20:25', dismissal_time: '20:35', days: ['Mon', 'Thu'] },
  { id: 'c_m2', name: 'M2', year: 2026, level_group: 'Middle', weekly_sessions: 2, sessions_per_month: 24, start_time: '16:40', end_time: '18:55', dismissal_time: '19:50', days: ['Tue', 'Fri'] },
  { id: 'c_m1', name: 'M1', year: 2026, level_group: 'Middle', weekly_sessions: 2, sessions_per_month: 24, start_time: '16:40', end_time: '18:55', dismissal_time: '19:50', days: ['Tue', 'Fri'] },
  { id: 'c_f4', name: 'F4', year: 2026, level_group: 'Elementary', weekly_sessions: 2, sessions_per_month: 24, start_time: '16:40', end_time: '18:55', dismissal_time: '19:50', days: ['Tue', 'Fri'] },
  { id: 'c_f3', name: 'F3', year: 2026, level_group: 'Elementary', weekly_sessions: 3, sessions_per_month: 24, start_time: '15:00', end_time: '16:35', dismissal_time: '17:25', days: ['Mon', 'Wed', 'Fri'] },
  { id: 'c_f2', name: 'F2', year: 2026, level_group: 'Elementary', weekly_sessions: 3, sessions_per_month: 24, start_time: '15:00', end_time: '16:35', dismissal_time: '17:25', days: ['Mon', 'Wed', 'Fri'] },
  { id: 'c_f1b', name: 'F1b', year: 2026, level_group: 'Elementary', weekly_sessions: 2, sessions_per_month: 24, start_time: '16:40', end_time: '18:55', dismissal_time: '19:50', days: ['Tue', 'Fri'] },
  { id: 'c_f1a', name: 'F1a', year: 2026, level_group: 'Elementary', weekly_sessions: 2, sessions_per_month: 24, start_time: '16:40', end_time: '18:55', dismissal_time: '19:50', days: ['Tue', 'Fri'] },
  { id: 'c_r3', name: 'R3a/R3b', year: 2026, level_group: 'Elementary', weekly_sessions: 3, sessions_per_month: 24, start_time: '15:00', end_time: '16:35', dismissal_time: '17:25', days: ['Mon', 'Wed', 'Fri'] },
  { id: 'c_r1', name: 'R1a/R1b', year: 2026, level_group: 'Elementary', weekly_sessions: 3, sessions_per_month: 24, start_time: '15:00', end_time: '16:35', dismissal_time: '17:25', days: ['Mon', 'Wed', 'Thu'] },
  { id: 'c_a5', name: 'A5', year: 2026, level_group: 'Elementary', weekly_sessions: 3, sessions_per_month: 24, start_time: '16:40', end_time: '18:10', dismissal_time: '19:00', days: ['Mon', 'Wed', 'Thu'] },
  { id: 'c_a4b', name: 'A4b', year: 2026, level_group: 'Elementary', weekly_sessions: 2, sessions_per_month: 24, start_time: '16:40', end_time: '18:55', dismissal_time: '19:50', days: ['Mon', 'Thu'] },
  { id: 'c_a4a', name: 'A4a', year: 2026, level_group: 'Elementary', weekly_sessions: 2, sessions_per_month: 24, start_time: '16:40', end_time: '18:55', dismissal_time: '19:50', days: ['Mon', 'Thu'] },
  { id: 'c_a3', name: 'A3', year: 2026, level_group: 'Elementary', weekly_sessions: 3, sessions_per_month: 24, start_time: '16:40', end_time: '18:10', dismissal_time: '19:00', days: ['Mon', 'Wed', 'Thu'] },
  { id: 'c_a2b', name: 'A2b', year: 2026, level_group: 'Elementary', weekly_sessions: 3, sessions_per_month: 24, start_time: '15:50', end_time: '17:25', dismissal_time: '18:10', days: ['Mon', 'Thu', 'Fri'] },
  { id: 'c_a2a', name: 'A2a', year: 2026, level_group: 'Elementary', weekly_sessions: 3, sessions_per_month: 24, start_time: '16:40', end_time: '18:10', dismissal_time: '19:00', days: ['Tue', 'Thu', 'Fri'] },
  { id: 'c_a1b', name: 'A1b', year: 2026, level_group: 'Elementary', weekly_sessions: 3, sessions_per_month: 24, start_time: '15:50', end_time: '17:25', dismissal_time: '18:10', days: ['Tue', 'Wed', 'Fri'] },
  { id: 'c_a1a', name: 'A1a', year: 2026, level_group: 'Elementary', weekly_sessions: 3, sessions_per_month: 24, start_time: '15:00', end_time: '16:35', dismissal_time: '17:25', days: ['Tue', 'Thu', 'Fri'] },
  { id: 'c_e3', name: 'E3', year: 2026, level_group: 'Kinder', weekly_sessions: 2, sessions_per_month: 24, start_time: '16:40', end_time: '18:00', days: ['Tue', 'Fri'] },
  { id: 'c_g3', name: 'G3', year: 2026, level_group: 'Kinder', weekly_sessions: 3, sessions_per_month: 24, start_time: '15:00', end_time: '16:35', days: ['Mon', 'Wed', 'Thu'] },
  { id: 'c_g2', name: 'G2', year: 2026, level_group: 'Kinder', weekly_sessions: 3, sessions_per_month: 24, start_time: '15:00', end_time: '16:35', days: ['Mon', 'Wed', 'Thu'] },
  { id: 'c_g1', name: 'G1', year: 2026, level_group: 'Kinder', weekly_sessions: 3, sessions_per_month: 24, start_time: '15:00', end_time: '16:35', days: ['Mon', 'Wed', 'Thu'] },
  { id: 'c_e1a', name: 'E1a', year: 2026, level_group: 'Kinder', weekly_sessions: 2, sessions_per_month: 24, start_time: '16:40', end_time: '18:00', dismissal_time: '18:10', days: ['Mon', 'Wed'] },
  { id: 'c_e1b', name: 'E1b', year: 2026, level_group: 'Kinder', weekly_sessions: 2, sessions_per_month: 24, start_time: '16:40', end_time: '18:00', dismissal_time: '18:10', days: ['Mon', 'Wed'] },
];

export const SAMPLE_BOOKS: Book[] = [
  // G1
  { id: 'b_g1_1', category: 'c_reading', level: 'G1', name: 'Phonics Show 1/ Readers', total_units: 10, unit_type: 'unit' },
  { id: 'b_g1_2', category: 'c_speaking', level: 'G1', name: 'I can speak English S1', total_units: 10, unit_type: 'unit' },
  // G2
  { id: 'b_g2_1', category: 'c_reading', level: 'G2', name: 'Phonics Friends 2', total_units: 10, unit_type: 'unit' },
  { id: 'b_g2_2', category: 'c_speaking', level: 'G2', name: 'I can speak English S2', total_units: 10, unit_type: 'unit' },
  { id: 'b_g2_3', category: 'c_voca', level: 'G2', name: 'Voca point 1', total_units: 10, unit_type: 'day' },
  // G3
  { id: 'b_g3_1', category: 'c_reading', level: 'G3', name: 'Phonics Show 4', total_units: 10, unit_type: 'unit' },
  { id: 'b_g3_2', category: 'c_speaking', level: 'G3', name: 'I can speak English 1', total_units: 10, unit_type: 'unit' },
  { id: 'b_g3_3', category: 'c_voca', level: 'G3', name: 'Voca point 2', total_units: 10, unit_type: 'day' },
  // A1a (Ground Up)
  { id: 'b_a1a_1', category: 'c_reading', level: 'A1a', name: 'WS Starter 1', total_units: 10, unit_type: 'unit' },
  { id: 'b_a1a_2', category: 'c_reading', level: 'A1a', name: 'WS Starter 3', total_units: 10, unit_type: 'unit' },
  { id: 'b_a1a_3', category: 'c_speaking', level: 'A1a', name: 'I can speak English 2', total_units: 10, unit_type: 'unit' },
  { id: 'b_a1a_4', category: 'c_speaking', level: 'A1a', name: 'I can speak English 3', total_units: 10, unit_type: 'unit' },
  { id: 'b_a1a_5', category: 'c_voca', level: 'A1a', name: 'Voca point 3', total_units: 10, unit_type: 'day' },
  { id: 'b_a1a_6', category: 'c_voca', level: 'A1a', name: 'Voca point 4', total_units: 10, unit_type: 'day' },
  // A1b
  { id: 'b_a1b_1', category: 'c_reading', level: 'A1b', name: 'WS Basic 2', total_units: 10, unit_type: 'unit' },
  { id: 'b_a1b_2', category: 'c_reading', level: 'A1b', name: 'WS Basic 3', total_units: 10, unit_type: 'unit' },
  { id: 'b_a1b_3', category: 'c_reading', level: 'A1b', name: 'Tropy 9 1 C1.2', total_units: 16, unit_type: 'day' },
  { id: 'b_a1b_4', category: 'c_reading', level: 'A1b', name: 'Tropy 9 1 C3 2A1', total_units: 16, unit_type: 'day' },
  { id: 'b_a1b_5', category: 'c_speaking', level: 'A1b', name: 'Everyone Speak Kids 3', total_units: 10, unit_type: 'unit' },
  { id: 'b_a1b_6', category: 'c_voca', level: 'A1b', name: '200words 3', total_units: 10, unit_type: 'day' },
  // A2a
  { id: 'b_a2a_1', category: 'c_reading', level: 'A2a', name: 'All new very easy true stories(8u)', total_units: 8, unit_type: 'unit' },
  { id: 'b_a2a_2', category: 'c_reading', level: 'A2a', name: 'WS Intermediate 1', total_units: 10, unit_type: 'unit' },
  { id: 'b_a2a_3', category: 'c_reading', level: 'A2a', name: 'Tropy 9 2 A3/ 2B1', total_units: 16, unit_type: 'day' },
  { id: 'b_a2a_4', category: 'c_reading', level: 'A2a', name: 'Tropy 9 2B3/ 2C1', total_units: 16, unit_type: 'day' },
  { id: 'b_a2a_5', category: 'c_grammar', level: 'A2a', name: 'Grammar point 1', total_units: 10, unit_type: 'unit' },
  { id: 'b_a2a_6', category: 'c_grammar', level: 'A2a', name: 'Grammar point 2', total_units: 10, unit_type: 'unit' },
  { id: 'b_a2a_7', category: 'c_writing', level: 'A2a', name: '5W1H', total_units: 10, unit_type: 'unit' },
  { id: 'b_a2a_8', category: 'c_writing', level: 'A2a', name: 'tense writing 1-1', total_units: 10, unit_type: 'unit' },
  // A2b
  { id: 'b_a2b_1', category: 'c_reading', level: 'A2b', name: 'WS Intermediate 2', total_units: 10, unit_type: 'unit' },
  { id: 'b_a2b_2', category: 'c_reading', level: 'A2b', name: 'WS Intermediate 3', total_units: 10, unit_type: 'unit' },
  { id: 'b_a2b_3', category: 'c_reading', level: 'A2b', name: 'Tropy 9 2C3/ 3A1', total_units: 16, unit_type: 'day' },
  { id: 'b_a2b_4', category: 'c_reading', level: 'A2b', name: 'Tropy 9 3A3/ 3B1', total_units: 16, unit_type: 'day' },
  { id: 'b_a2b_5', category: 'c_grammar', level: 'A2b', name: 'Grammar point 3', total_units: 10, unit_type: 'unit' },
  { id: 'b_a2b_6', category: 'c_grammar', level: 'A2b', name: 'Grammar point 4', total_units: 10, unit_type: 'unit' },
  { id: 'b_a2b_7', category: 'c_writing', level: 'A2b', name: 'paragrah writing', total_units: 10, unit_type: 'unit' },
  { id: 'b_a2b_8', category: 'c_writing', level: 'A2b', name: 'tense writing 2-1', total_units: 10, unit_type: 'unit' },
  // A3a (Power Up)
  { id: 'b_a3a_1', category: 'c_reading', level: 'A3a', name: 'True stories 1B', total_units: 10, unit_type: 'unit' },
  { id: 'b_a3a_2', category: 'c_reading', level: 'A3a', name: 'Our world 4A', total_units: 10, unit_type: 'unit' },
  { id: 'b_a3a_3', category: 'c_reading', level: 'A3a', name: 'Tropy 9 3B23C1', total_units: 16, unit_type: 'day' },
  { id: 'b_a3a_4', category: 'c_reading', level: 'A3a', name: 'Tropy 9 3C2/ 3C3', total_units: 16, unit_type: 'day' },
  { id: 'b_a3a_5', category: 'c_grammar', level: 'A3a', name: 'Aha Grammar 2 (My First Grammar 2)', total_units: 10, unit_type: 'unit' },
  { id: 'b_a3a_6', category: 'c_writing', level: 'A3a', name: 'Andover Writing 1', total_units: 10, unit_type: 'unit' },
  // A3b
  { id: 'b_a3b_1', category: 'c_reading', level: 'A3b', name: 'Subject link 4', total_units: 10, unit_type: 'unit' },
  { id: 'b_a3b_2', category: 'c_reading', level: 'A3b', name: 'Our world 5A', total_units: 10, unit_type: 'unit' },
  { id: 'b_a3b_3', category: 'c_reading', level: 'A3b', name: 'Tropy 9 4A1/ 4A2', total_units: 16, unit_type: 'day' },
  { id: 'b_a3b_4', category: 'c_reading', level: 'A3b', name: 'Tropy 9 4A3/ 4B1', total_units: 16, unit_type: 'day' },
  { id: 'b_a3b_5', category: 'c_grammar', level: 'A3b', name: 'Aha Grammar 3 (My First Grammar 3)', total_units: 10, unit_type: 'unit' },
  { id: 'b_a3b_6', category: 'c_writing', level: 'A3b', name: 'Andover Writing 2', total_units: 10, unit_type: 'unit' },
  // A4a
  { id: 'b_a4a_1', category: 'c_reading', level: 'A4a', name: 'Reading Juice Plus 1', total_units: 10, unit_type: 'unit' },
  { id: 'b_a4a_2', category: 'c_reading', level: 'A4a', name: 'Brick Reading 300-2', total_units: 10, unit_type: 'unit' },
  { id: 'b_a4a_3', category: 'c_reading', level: 'A4a', name: 'Tropy 9 4B2/ 4B3', total_units: 16, unit_type: 'day' },
  { id: 'b_a4a_4', category: 'c_reading', level: 'A4a', name: 'Tropy 9 4C1/ 4C2', total_units: 16, unit_type: 'day' },
  { id: 'b_a4a_5', category: 'c_grammar', level: 'A4a', name: 'My next Grammar 1 (Grammar Success1)', total_units: 10, unit_type: 'unit' },
  { id: 'b_a4a_6', category: 'c_writing', level: 'A4a', name: 'Andover Writing 3', total_units: 10, unit_type: 'unit' },
  // A4b
  { id: 'b_a4b_1', category: 'c_reading', level: 'A4b', name: 'Ted Talks 21st 1', total_units: 10, unit_type: 'unit' },
  { id: 'b_a4b_2', category: 'c_reading', level: 'A4b', name: 'Junior Debate Starter + Reading Success 3', total_units: 10, unit_type: 'unit' },
  { id: 'b_a4b_3', category: 'c_reading', level: 'A4b', name: 'Tropy 9 4C3/ 4C2', total_units: 16, unit_type: 'day' },
  { id: 'b_a4b_4', category: 'c_reading', level: 'A4b', name: 'Tropy 9 5A1/ 5A2', total_units: 16, unit_type: 'day' },
  { id: 'b_a4b_5', category: 'c_grammar', level: 'A4b', name: 'My next Grammar 2 (Grammar Success1)', total_units: 10, unit_type: 'unit' },
  { id: 'b_a4b_6', category: 'c_writing', level: 'A4b', name: 'Andover Writing 4', total_units: 10, unit_type: 'unit' },
  // A5
  { id: 'b_a5_1', category: 'c_reading', level: 'A5', name: 'Reading Juice Plus 3', total_units: 10, unit_type: 'unit' },
  { id: 'b_a5_2', category: 'c_reading', level: 'A5', name: 'My First Chapter Books (4 Books)', total_units: 4, unit_type: 'unit' },
  { id: 'b_a5_3', category: 'c_reading', level: 'A5', name: 'Tropy 9 5A3/ 5B1', total_units: 16, unit_type: 'day' },
  { id: 'b_a5_4', category: 'c_reading', level: 'A5', name: 'Tropy 9 5B2/ 5B3', total_units: 16, unit_type: 'day' },
  { id: 'b_a5_5', category: 'c_speaking', level: 'A5', name: 'M원리 / CS', total_units: 10, unit_type: 'unit' },
  { id: 'b_a5_6', category: 'c_grammar', level: 'A5', name: 'My next Grammar 3 (Grammar Success1)', total_units: 10, unit_type: 'unit' },
  { id: 'b_a5_7', category: 'c_writing', level: 'A5', name: 'Creative Journal 1', total_units: 10, unit_type: 'unit' },
  // F1 (Asset)
  { id: 'b_f1_1', category: 'c_reading', level: 'F1', name: 'intoreading 3.1', total_units: 10, unit_type: 'unit' },
  { id: 'b_f1_2', category: 'c_grammar', level: 'F1', name: 'Grammar Engine 1', total_units: 10, unit_type: 'unit' },
  { id: 'b_f1_3', category: 'c_writing', level: 'F1', name: 'Creative Journal 1', total_units: 10, unit_type: 'unit' },
  { id: 'b_f1_4', category: 'c_voca', level: 'F1', name: 'voca & into (에듀스프링)', total_units: 10, unit_type: 'unit' },
  // F2
  { id: 'b_f2_1', category: 'c_reading', level: 'F2', name: 'intoreading 3.3', total_units: 10, unit_type: 'unit' },
  { id: 'b_f2_2', category: 'c_reading', level: 'F2', name: 'My First Chapter Books (4 Books)', total_units: 4, unit_type: 'unit' },
  { id: 'b_f2_3', category: 'c_grammar', level: 'F2', name: 'Grammar Engine 2', total_units: 10, unit_type: 'unit' },
  { id: 'b_f2_4', category: 'c_writing', level: 'F2', name: 'Creative Journal 2', total_units: 10, unit_type: 'unit' },
  { id: 'b_f2_5', category: 'c_voca', level: 'F2', name: 'voca & into (에듀스프링)', total_units: 10, unit_type: 'unit' },
  // F3
  { id: 'b_f3_1', category: 'c_reading', level: 'F3', name: 'intoreading 4.1', total_units: 10, unit_type: 'unit' },
  { id: 'b_f3_2', category: 'c_reading', level: 'F3', name: 'AMI Presentation Starter +Reading Success 4)', total_units: 10, unit_type: 'unit' },
  { id: 'b_f3_3', category: 'c_grammar', level: 'F3', name: 'Grammar Engine 3', total_units: 10, unit_type: 'unit' },
  { id: 'b_f3_4', category: 'c_voca', level: 'F3', name: 'voca & into (에듀스프링)', total_units: 10, unit_type: 'unit' },
  // Middle School - M1A
  { id: 'b_m1a_1', category: 'c_reading', level: 'M1A', name: 'Subject link 5', total_units: 10, unit_type: 'unit' },
  { id: 'b_m1a_2', category: 'c_reading', level: 'M1A', name: 'Reading for Today 1 Themes', total_units: 10, unit_type: 'unit' },
  { id: 'b_m1a_3', category: 'c_reading', level: 'M1A', name: 'Korean Curriculum - Social Studies & Science (5Gr+6Gr)', total_units: 10, unit_type: 'unit' },
  { id: 'b_m1a_4', category: 'c_speaking', level: 'M1A', name: 'M원리 / CS', total_units: 10, unit_type: 'unit' },
  { id: 'b_m1a_5', category: 'c_voca', level: 'M1A', name: 'voca (에듀스프링)', total_units: 10, unit_type: 'unit' },
  { id: 'b_m1a_6', category: 'c_grammar', level: 'M1A', name: 'Grammar inside1', total_units: 10, unit_type: 'unit' },
  { id: 'b_m1a_7', category: 'c_writing', level: 'M1A', name: 'Masters Journal 1', total_units: 10, unit_type: 'unit' },
  { id: 'b_m1a_8', category: 'c_speaking', level: 'M1A', name: 'M원리', total_units: 10, unit_type: 'unit' },
  // M1B
  { id: 'b_m1b_1', category: 'c_reading', level: 'M1B', name: 'Chapter Books (4 Books)', total_units: 4, unit_type: 'unit' },
  { id: 'b_m1b_2', category: 'c_reading', level: 'M1B', name: '<Docu-English> Reading Explorer Foundation', total_units: 10, unit_type: 'unit' },
  { id: 'b_m1b_3', category: 'c_speaking', level: 'M1B', name: 'M원리', total_units: 10, unit_type: 'unit' },
  { id: 'b_m1b_4', category: 'c_voca', level: 'M1B', name: 'voca (에듀스프링)', total_units: 10, unit_type: 'unit' },
  { id: 'b_m1b_5', category: 'c_grammar', level: 'M1B', name: '중학 영문법 3800제 1', total_units: 10, unit_type: 'unit' },
  { id: 'b_m1b_6', category: 'c_writing', level: 'M1B', name: 'Masters Journal 2', total_units: 10, unit_type: 'unit' },
  // M2A
  { id: 'b_m2a_1', category: 'c_reading', level: 'M2A', name: 'Reading for Today 2 insights', total_units: 10, unit_type: 'unit' },
  { id: 'b_m2a_2', category: 'c_reading', level: 'M2A', name: '<Docu-English> Reading Explorer 1', total_units: 10, unit_type: 'unit' },
  { id: 'b_m2a_3', category: 'c_reading', level: 'M2A', name: 'English Newspaper Articles (the Teen Times)', total_units: 10, unit_type: 'unit' },
  { id: 'b_m2a_4', category: 'c_speaking', level: 'M2A', name: 'M원리', total_units: 10, unit_type: 'unit' },
  { id: 'b_m2a_5', category: 'c_voca', level: 'M2A', name: 'voca (에듀스프링)', total_units: 10, unit_type: 'unit' },
  { id: 'b_m2a_6', category: 'c_grammar', level: 'M2A', name: 'Grammar inside2', total_units: 10, unit_type: 'unit' },
  { id: 'b_m2a_7', category: 'c_writing', level: 'M2A', name: 'Masters Journal 3', total_units: 10, unit_type: 'unit' },
  // M2B
  { id: 'b_m2b_1', category: 'c_reading', level: 'M2B', name: 'Novels (3 Books)', total_units: 3, unit_type: 'unit' },
  { id: 'b_m2b_2', category: 'c_reading', level: 'M2B', name: '<Docu-English> Reading Explorer 2', total_units: 10, unit_type: 'unit' },
  { id: 'b_m2b_3', category: 'c_reading', level: 'M2B', name: 'English Newspaper Articles (the Teen Times)', total_units: 10, unit_type: 'unit' },
  { id: 'b_m2b_4', category: 'c_speaking', level: 'M2B', name: 'M원리', total_units: 10, unit_type: 'unit' },
  { id: 'b_m2b_5', category: 'c_voca', level: 'M2B', name: 'voca (에듀스프링)', total_units: 10, unit_type: 'unit' },
  { id: 'b_m2b_6', category: 'c_grammar', level: 'M2B', name: '중학 영문법 3800제 2', total_units: 10, unit_type: 'unit' },
  { id: 'b_m2b_7', category: 'c_writing', level: 'M2B', name: 'Masters Journal 4', total_units: 10, unit_type: 'unit' },
  // M3A
  { id: 'b_m3a_1', category: 'c_reading', level: 'M3A', name: 'What I believe 1', total_units: 10, unit_type: 'unit' },
  { id: 'b_m3a_2', category: 'c_reading', level: 'M3A', name: '<Docu-English> Reading Explorer 3', total_units: 10, unit_type: 'unit' },
  { id: 'b_m3a_3', category: 'c_reading', level: 'M3A', name: 'The Korea Times', total_units: 10, unit_type: 'unit' },
  { id: 'b_m3a_4', category: 'c_speaking', level: 'M3A', name: 'M원리', total_units: 10, unit_type: 'unit' },
  { id: 'b_m3a_5', category: 'c_voca', level: 'M3A', name: 'voca (에듀스프링)', total_units: 10, unit_type: 'unit' },
  { id: 'b_m3a_6', category: 'c_grammar', level: 'M3A', name: 'Grammar inside 3', total_units: 10, unit_type: 'unit' },
  { id: 'b_m3a_7', category: 'c_writing', level: 'M3A', name: 'Essay Writing 1', total_units: 10, unit_type: 'unit' },
  // M3B
  { id: 'b_m3b_1', category: 'c_reading', level: 'M3B', name: 'Novels (2 Books)', total_units: 2, unit_type: 'unit' },
  { id: 'b_m3b_2', category: 'c_reading', level: 'M3B', name: '<Docu-English> Reading for Today 3 Issues', total_units: 10, unit_type: 'unit' },
  { id: 'b_m3b_3', category: 'c_speaking', level: 'M3B', name: 'M원리', total_units: 10, unit_type: 'unit' },
  { id: 'b_m3b_4', category: 'c_voca', level: 'M3B', name: 'voca (에듀스프링)', total_units: 10, unit_type: 'unit' },
  { id: 'b_m3b_5', category: 'c_grammar', level: 'M3B', name: '중학 영문법 3800제 3', total_units: 10, unit_type: 'unit' },
  { id: 'b_m3b_6', category: 'c_writing', level: 'M3B', name: 'Essay Writing 2', total_units: 10, unit_type: 'unit' },
];
